version: '3.8'

services:
  frontend-service:
    build: ./services/frontend-service
    ports:
      - "3000:80"
    environment:
      - BACKEND_ALB_DNS=http://localhost:8086 # Frontend points to local host for backends

  booking-service:
    build: ./services/booking-service
    ports:
      - "8086:8086" # All backend services now run on port 8086

  flight-service:
    build: ./services/flight-service
    ports:
      - "8087:8086" # Host port 8087, container port 8086

  payment-service:
    build: ./services/payment-service
    ports:
      - "8088:8086" # Host port 8088, container port 8086