version: '3.8'

services:
  frontend-service:
    build: ./services/frontend-service
    ports:
      - "3000:80"

  booking-service:
    build: ./services/booking-service
    ports:
      - "8086:8086"

  flight-service:
    build: ./services/flight-service
    ports:
      - "8087:8086"
      
  payment-service:
    build: ./services/payment-service
    ports:
      - "8088:8086"